/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventKind = IDL.Variant({
  'Graduation' : IDL.Null,
  'Promotion' : IDL.Null,
  'Birthday' : IDL.Null,
  'Marriage' : IDL.Null,
  'NewJob' : IDL.Null,
  'NewBaby' : IDL.Null,
  'Other' : IDL.Null,
});
export const PostRequest = IDL.Record({
  'event' : EventKind,
  'customText' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeXOAuth' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'disconnectMyX' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMyXConnected' : IDL.Func([], [IDL.Bool], ['query']),
  'isXClientIdConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'postEventTweet' : IDL.Func([PostRequest], [IDL.Text], []),
  'setXClientId' : IDL.Func([IDL.Text], [], []),
  'startXOAuth' : IDL.Func([IDL.Text], [IDL.Text], []),
  'xPostTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'xTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventKind = IDL.Variant({
    'Graduation' : IDL.Null,
    'Promotion' : IDL.Null,
    'Birthday' : IDL.Null,
    'Marriage' : IDL.Null,
    'NewJob' : IDL.Null,
    'NewBaby' : IDL.Null,
    'Other' : IDL.Null,
  });
  const PostRequest = IDL.Record({
    'event' : EventKind,
    'customText' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeXOAuth' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'disconnectMyX' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMyXConnected' : IDL.Func([], [IDL.Bool], ['query']),
    'isXClientIdConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'postEventTweet' : IDL.Func([PostRequest], [IDL.Text], []),
    'setXClientId' : IDL.Func([IDL.Text], [], []),
    'startXOAuth' : IDL.Func([IDL.Text], [IDL.Text], []),
    'xPostTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'xTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };